apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "back-end.fullname" . }}
  labels:
    {{- include "back-end.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "back-end.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "back-end.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "back-end.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: db-migrator
          image: registry.steffbeckers.eu/recipes/db-migrator
          env:
            - name: ConnectionStrings__Default
              value: {{ .Values.global.app.connectionString }}
            - name: IdentityServer__Clients__Recipes_App__RootUrl
              value: "https://{{ .Values.global.app.domain }}"
            - name: IdentityServer__Clients__Recipes_Swagger__RootUrl
              value: "https://{{ .Values.global.app.domain }}"
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:80
            - name: AuthServer__Authority
              value: "https://{{ .Values.global.app.domain }}"
            - name: App__SelfUrl
              value: "https://{{ .Values.global.app.domain }}"
            - name: App__CorsOrigins
              value: "https://{{ .Values.global.app.domain }}"
            - name: App__RedirectAllowedUrls
              value: "https://{{ .Values.global.app.domain }}"
            - name: App__MultiTenancyDomainFormat
              value: "{0}.{{ .Values.global.app.domain }}"
            - name: ConnectionStrings__Default
              value: {{ .Values.global.app.connectionString }}
            - name: BlobStorage__Azure__ConnectionString
              value: {{ .Values.global.app.blobStorage.azure.connectionString }}
            - name: BlobStorage__Azure__ContainerName
              value: {{ .Values.global.app.blobStorage.azure.containerName }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
