{{- if .Values.ingress.enabled -}}
{{- $fullName := include "recipes.fullname" . -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ $fullName }}-ingress"
  labels:
    {{- include "front-end.labels" . | nindent 4 }}
    {{- include "back-end.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  tls:
    - hosts:
        - {{ .Values.global.app.domain }}
        - "*.{{ .Values.global.app.domain }}"
      secretName: "{{ .Values.global.app.domain }}-tls"
  rules:
    - host: {{ .Values.global.app.domain }}
      http: &http_rules
        paths:
          - path: /.well-known
            pathType: Prefix
            backend:
              service:
                name: "{{ $fullName }}-back-end"
                port:
                  number: 80
          - path: /__bundles
            pathType: Prefix
            backend:
              service:
                name: "{{ $fullName }}-back-end"
                port:
                  number: 80
          - path: /Abp
            pathType: Prefix
            backend:
              service:
                name: "{{ $fullName }}-back-end"
                port:
                  number: 80
          - path: /account
            pathType: Prefix
            backend:
              service:
                name: "{{ $fullName }}-back-end"
                port:
                  number: 80
          - path: /Account
            pathType: Prefix
            backend:
              service:
                name: "{{ $fullName }}-back-end"
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: "{{ $fullName }}-back-end"
                port:
                  number: 80
          - path: /connect
            pathType: Prefix
            backend:
              service:
                name: "{{ $fullName }}-back-end"
                port:
                  number: 80
          - path: /libs
            pathType: Prefix
            backend:
              service:
                name: "{{ $fullName }}-back-end"
                port:
                  number: 80
          - path: /swagger
            pathType: Prefix
            backend:
              service:
                name: "{{ $fullName }}-back-end"
                port:
                  number: 80
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: "{{ $fullName }}-front-end"
                port:
                  number: 80
    - host: "*.{{ .Values.global.app.domain }}"
      http: *http_rules
{{- end }}
